### ISSUE TITLE
Unable to get transactions from DKB

### ISSUE THREAD

**Issue by se7entynine** [bnw/firefly-iii-fints-importer#130]
Hey, 

I am unable to get information from my bank ( DKB ). With 910, 911, 912 or 913, but every method fails with a similar error message as this one: 

910,911,912,913: 
`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9900 (wrt seg 4): Anmeldung fehlgeschlagen. (MBV07390100153) FinTS warnings: 3905 (global): Es wurde keine Challenge erzeugt. 3920 (wrt seg 4): Zugelassene Zwei-Schritt-Verfahren für den Benutzer. [910, 911, 912, 913] Request segments: HKVVB:4:3+12+0+0+0F4CA8A225AC9799E6BE3F334+1.0' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(263): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /app/Login.php(23): Fhp\FinTs->login() #4 /app/TanHandler.php(41): App\StepFunction\{closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/Login.php(21): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #7 /app/index.php(59): App\StepFunction\Login() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`

The process in my bank is with either username the same: username/password + app confirmation or chiptan.
Firefly and the rest runs on docker.

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - ${PWD}/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 7777:8080
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - ${PWD}/firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '7776:8080'
    depends_on:
      - app
    env_file: .importer.env

  fints-importer:
    image: benkl/firefly-iii-fints-importer
    volumes:
        - ${PWD}/fints-importer/data/configurations:/app/configurations
    ports: 
        - 7778:8080
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
```

Personal access token is used and I also tried different urls like:
http://app:7777, http://192.168.10.104:7777 or http://app:8080 like the importer. 
Double checked BLZ and fints-url. The normal bank page login works so it's not a problem on their side.

These are the informations from my bank about fints:

> 
> Bankleitzahl: 120 300 00
> Sicherheitsmedium: HBCI-PIN mit chipTAN/TAN2go
> Benutzerkennung: Dein Anmeldename
> Kunden-ID: Dieses Feld bitte frei lassen
> HBCI-Version: FinTS 3.0
> Kommunikationsadresse: https://banking-dkb.s-fints-pt-dkb.de/fints30

Any idea what is wrong in my setup or is it a bug?
