### ISSUE TITLE
"cURL error 28: Connection timeout" in GetAccountsRequest.php(80)

### ISSUE THREAD

**Issue by cmwolke-gamedesign** [bnw/firefly-iii-fints-importer#163]
Hi! First time user so I might have made a mistake setting up, any help will be much appreciated.

After getting the mobile tan request page the following error is displayed:

`Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: Tried "http://1.2.3.4:85/api/v1/accounts?type=asset&page=1&limit=250" 5 times but failed: cURL error 28: Connection timeout after 3141 ms (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://1.2.3.4:85/api/v1/accounts?type=asset&page=1&limit=250 in /vendor/firefly-iii/api-support-classes/src/Request/Request.php:202 Stack trace: #0 /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(80): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() #1 /app/ChooseAccount.php(38): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #2 /app/index.php(63): App\StepFunction\ChooseAccount() #3 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 202`

I tried curl-ing the api with my personal access token as bearer token, and it *works* from the localhost, and via postman on another machine. 

This is my docker-compose.yml:

```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 85:8080
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: database.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8082/api/v1/cron/{CRONKEY};echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

  fints-importer:
    image: benkl/firefly-iii-fints-importer
    container_name: firefly-iii-fints-importer
    volumes:
      - ./firefly-iii-fints-importer/data/configurations:/app/configurations
    ports:
      - 8085:8080
    networks:
      - firefly_iii


volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```
