### ISSUE TITLE
Getting exec format error when running with docker compose

### ISSUE THREAD

**Issue by lole-elol** [bnw/firefly-iii-fints-importer#77]
I am getting this error message when starting the container with `docker-compose up`
This setup is running on a Raspberry Pi 4.  I got an instance of Firefly-III also running in docker

```
myuser@pi:~/firefly-iii-fints-importer $ docker-compose up
firefly-iii-fints-importer_app_1 is up-to-date
Attaching to firefly-iii-fints-importer_app_1
app_1  | exec /usr/local/bin/php: exec format error
firefly-iii-fints-importer_app_1 exited with code 1
app_1  | exec /usr/local/bin/php: exec format error
app_1  | exec /usr/local/bin/php: exec format error

```
My docker-compose.yml looks like this:

```
version: '3'
services:
    app:
        image: benkl/firefly-iii-fints-importer
        restart: always
        volumes:
            - ./data/configurations:/app/configurations
        ports:
            - 6000:8080
```
